### ISSUE TITLE
Some papers related to this tool

### ISSUE THREAD

**Issue by tsrobcvai** [njzhangyifei/keyframe#4]
Thank you for your nice work! I am interested in the specific algorithm used in this tool, can you please provide some papers related to this tool?

**Comment by njzhangyifei** [comment]
No paper published on this tool. Happy to work with you and extend it if this is your area of interest. 

There’s a lot more work by considering 3d movement of the camera as well. There should be some far better method in terms of accuracy.

Haven’t been looking at this area for some time.
